<a href="https://colab.research.google.com/github/agustin-sarasua/workshop-categorization/blob/master/intro_python_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

# Python Basics

Function Definition

In [0]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

Optional parameters

In [0]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


Assing functions to variables

In [0]:
a = add_numbers
a(1,2)

3

In [0]:
type('This is a string')

str

In [0]:
type(add_numbers)

function

Tuples are inmutable

In [0]:
x = (1, 'a', 2, 'b')
type(x)

tuple

Lists are mutable

In [0]:
x = [1, 'a', 2, 'b']
type(x)

list

In [0]:
x.append('Something')
x

[1, 'a', 2, 'b', 'Something', 'Something']

For loops

In [0]:
for item in x:
    print(item)

1
a
2
b
Something
Something


Concat Lists

In [0]:
[1,2] + [3,4]

[1, 2, 3, 4]

Repeat list

In [0]:
[1]*3

[1, 1, 1]

Slice from string

In [0]:
x = 'This is a string'
print(x[:2]) # First 2 chars
print(x[-1]) # Last char
print(x[-4:-2]) # Slice starting from the end 

Th
g
ri


Dictionaries

In [0]:
x = {'A':1, 'B': 2}
x['A']

1

In [0]:
x['A']=None
x['A']

# Numpy Basics
- Linear Algebra
- Provee high-performance multidimensional arrays y tools para trabajar con éstos.

## Arrays
Son grillas de valores, todos del mismo tipo.

In [0]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [0]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)

(2, 3)


In [0]:
print(b[0, 1])
print(b[1, 0])

2
4


Useful functions

In [0]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [0]:
np.full((2,3), 3)

array([[3, 3, 3],
       [3, 3, 3]])

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
a = np.random.random((2,2))
a

array([[0.00418121, 0.19036664],
       [0.89457566, 0.741604  ]])

In [0]:
print(a.dtype) 

float64


## Vectorization

Vector multiplication using for loops

In [0]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
    
print("Non vectorized version: " + str(1000*(toc-tic)) + " ms")
print("Output value:", c)

Non vectorized version: 439.00537490844727 ms
Output value: 250001.99902139333


Vector multiplication using vectorized version

In [0]:
tic = time.time()
c = np.dot(a, b)
toc = time.time()

print("Vectorized version: " + str(1000*(toc-tic)) + " ms")
print("Output value:", c)

Vectorized version: 3.243684768676758 ms
Output value: 250001.99902139607


# Pandas

## Series

In [0]:
import pandas as pd
pd.Series?

In [0]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [0]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [0]:
animals = ['Tiger', 'Bear', None]
pd.Series(animals)

0    Tiger
1     Bear
2     None
dtype: object

In [0]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [0]:
import numpy as np
np.nan == None

False

In [0]:
np.nan == np.nan

False

In [0]:
np.isnan(np.nan)

True

Querying a series

In [0]:
a = {'A': 'VA',
          'B': 'VB',
          'C': 'VC',
          'D': 'VD'}
s = pd.Series(a)
s

A    VA
B    VB
C    VC
D    VD
dtype: object

In [0]:
s.iloc[3]

'VD'

In [0]:
s.loc['D']

'VD'

In [0]:
s[3]

'VD'

In [0]:
s['D']

'VD'

In [0]:
a = {10: 'VA',
          11: 'VB',
          12: 'VC',
          13: 'VD'}
s = pd.Series(a)

In [0]:
s[0]

KeyError: ignored

## DataFrame

In [0]:
d = {'one': pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
     'two': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
df.head()

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [0]:
print(df.index)

Index(['a', 'b', 'c', 'd'], dtype='object')


In [0]:
df.loc['c']

one    3.0
two    3.0
Name: c, dtype: float64

In [0]:
df.T

a    b    c    d
one  1.0  2.0  3.0  NaN
two  1.0  2.0  3.0  4.0

In [0]:
df.T.loc['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [0]:
df.drop('c')

one  two
a  1.0  1.0
b  2.0  2.0
d  NaN  4.0

In [0]:
df

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [0]:
copy_df = df.copy()
copy_df = copy_df.drop('c')
copy_df

one  two
a  2.0  1.0
b  2.0  2.0
d  NaN  4.0

In [0]:
df

one  two
a  2.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

Query a DataFrame

In [0]:
df['two'] > 2

a    False
b    False
c     True
d     True
Name: two, dtype: bool

In [0]:
df.where(df['two'] > 2)

one  two
a  NaN  NaN
b  NaN  NaN
c  3.0  3.0
d  NaN  4.0

In [0]:
df.where(df['two'] > 2).dropna()

one  two
c  3.0  3.0

In [0]:
df[df['two'] > 2]

one  two
c  3.0  3.0
d  NaN  4.0